### ISSUE TITLE
Проблемы с контрактами

### ISSUE THREAD

**Issue by Grong1515** [AlbertoWhite/GuarantSystem#3]
> Error: VM Exception while processing transaction: invalid opcode

ошибка возникает при деплое Main контракта, и при вызове registerManufacturer (остальные еще не пробовал, но сорее всего тоже будет)

Дима предложил избавиться от деплоеров

В первую очередь нужен рабочий mainContract и методы создания m/v/sc

**Comment by Grong1515** [comment]
если я закомментирую в конструкторе мейна строки с инициализацией деплоеров, и оставлю только одну, то деплой происходит

**Comment by ymeister** [comment]
Деплой Main контракта решён разделением на файлы.
Ошибка при registerManufacture - проблема сервера.
